// <auto-generated />
using System;
using HShop2024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HShop2024.Migrations
{
    [DbContext(typeof(Hshop2023Context))]
    [Migration("20250115031947_UpdateUserModel")]
    partial class UpdateUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HShop2024.Data.ChiTietHd", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCt"));

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaHh")
                        .HasColumnType("int")
                        .HasColumnName("MaHH");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaCt")
                        .HasName("PK_OrderDetails");

                    b.HasIndex("MaHh");

                    b.ToTable("ChiTietHD", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.HangHoa", b =>
                {
                    b.Property<int>("MaHh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHh"));

                    b.Property<double?>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFantastic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaNcc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaDonVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NgaySX")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLanXem")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenAlias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHH");

                    b.HasKey("MaHh")
                        .HasName("PK_Products");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNcc");

                    b.ToTable("HangHoa", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<string>("CachThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Cash");

                    b.Property<string>("CachVanChuyen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Airline");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(((1)/(1))/(1900))");

                    b.Property<double>("PhiVanChuyen")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHd")
                        .HasName("PK_Orders");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.HoiDap", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<string>("CauHoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaHh")
                        .HasColumnType("int")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayDua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHd");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoiDap", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool>("HieuLuc")
                        .HasColumnType("bit");

                    b.Property<string>("Hinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Photo.gif");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("NgaySinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RandomKey")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.Property<int?>("Xu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaKh")
                        .HasName("PK_Customers");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoaiAlias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai")
                        .HasName("PK_Categories");

                    b.ToTable("Loai", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LoginHis__3214EC07CE316663");

                    b.HasIndex("MaNv");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.NhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiLienLac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNcc")
                        .HasName("PK_Suppliers");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNv");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.PhanCong", b =>
                {
                    b.Property<int>("MaPc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPc"));

                    b.Property<bool?>("HieuLuc")
                        .HasColumnType("bit");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaPb")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("MaPB");

                    b.Property<DateTime?>("NgayPc")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayPC");

                    b.HasKey("MaPc");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaPb");

                    b.ToTable("PhanCong", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.PhongBan", b =>
                {
                    b.Property<string>("MaPb")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("MaPB");

                    b.Property<string>("TenPb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenPB");

                    b.Property<string>("ThongTin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPb");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.TrangThai", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThai", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int?>("MaHh")
                        .HasColumnType("int")
                        .HasColumnName("MaHH");

                    b.Property<int?>("TimesUsed")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Voucher__3214EC0791E65616");

                    b.HasIndex("MaHh");

                    b.HasIndex(new[] { "Code" }, "UQ__Voucher__A25C5AA76CEC4E53")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.YeuThich", b =>
                {
                    b.Property<int>("MaYt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaYT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYt"));

                    b.Property<int?>("MaHh")
                        .HasColumnType("int")
                        .HasColumnName("MaHH");

                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayChon")
                        .HasColumnType("datetime");

                    b.HasKey("MaYt")
                        .HasName("PK_Favorites");

                    b.HasIndex("MaHh");

                    b.HasIndex("MaKh");

                    b.ToTable("YeuThich", (string)null);
                });

            modelBuilder.Entity("HShop2024.Data.ChiTietHd", b =>
                {
                    b.HasOne("HShop2024.Data.HangHoa", "MaHhNavigation")
                        .WithMany("ChiTietHds")
                        .HasForeignKey("MaHh")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.Navigation("MaHhNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.HangHoa", b =>
                {
                    b.HasOne("HShop2024.Data.Loai", "MaLoaiNavigation")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.HasOne("HShop2024.Data.NhaCungCap", "MaNccNavigation")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaNcc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Suppliers");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.HoaDon", b =>
                {
                    b.HasOne("HShop2024.Data.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("HShop2024.Data.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.HasOne("HShop2024.Data.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaTrangThai")
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_TrangThai");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.HoiDap", b =>
                {
                    b.HasOne("HShop2024.Data.HangHoa", "MaHhNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK_HoiDap_HangHoa");

                    b.HasOne("HShop2024.Data.NhanVien", "MaNvNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HoiDap_NhanVien");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.LoginHistory", b =>
                {
                    b.HasOne("HShop2024.Data.NhanVien", "MaNvNavigation")
                        .WithMany("LoginHistories")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK_LoginHistory_NhanVien");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.PhanCong", b =>
                {
                    b.HasOne("HShop2024.Data.NhanVien", "MaNvNavigation")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK_PhanCong_NhanVien");

                    b.HasOne("HShop2024.Data.PhongBan", "MaPbNavigation")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaPb")
                        .IsRequired()
                        .HasConstraintName("FK_PhanCong_PhongBan");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaPbNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.Voucher", b =>
                {
                    b.HasOne("HShop2024.Data.HangHoa", "MaHhNavigation")
                        .WithMany("Vouchers")
                        .HasForeignKey("MaHh")
                        .HasConstraintName("FK_Voucher_HangHoa");

                    b.Navigation("MaHhNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.YeuThich", b =>
                {
                    b.HasOne("HShop2024.Data.HangHoa", "MaHhNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaHh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_YeuThich_HangHoa");

                    b.HasOne("HShop2024.Data.KhachHang", "MaKhNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Favorites_Customers");

                    b.Navigation("MaHhNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("HShop2024.Data.HangHoa", b =>
                {
                    b.Navigation("ChiTietHds");

                    b.Navigation("HoiDaps");

                    b.Navigation("Vouchers");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("HShop2024.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("HShop2024.Data.Loai", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("HShop2024.Data.NhaCungCap", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("HShop2024.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HoiDaps");

                    b.Navigation("LoginHistories");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("HShop2024.Data.PhongBan", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("HShop2024.Data.TrangThai", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
